language: node_js
node_js:
- '12'
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: krevetochka-delivery
  api_key:
    secure: wtxOhNkmwiSkpAqnz4TAOMLC4iF84BF7Kdy1MyeMO3p3czun/Rj0GPZwrE/YyewFoS6XO/eJ1UZkvvteoPFXPaAIt8+3RqTiwAqilv2N5QgeFG6cZloM/NRjK103r/WotoPBv8TgwwFvMl4GZkF5/GrJgbbvgAWNpAvUOm/fuAalPJm9cfVEOFeAOGVoWZzfDYqn3ZMWPsmL9ZSHmUkGWDyr+L1Or9ig+/4966QjLWhiwEfNnF2K3B1wfmd2GKuhMqovUx+yXTaQWOSktwaMlzUEtA7jge2jWCUvPGdCvGas98dwRif6J2qr8uYCevdIWMjreVwwLIqBie86tBhz74B2AtowK7Yhh5v49O2++c/Dh6HQ3KgZLyWoCxMEol0Vp+/rgFWP2pKmo49iDT+44uouvmHN8WsdEC0S5aZ51s2VZhlLlhlY86C/uIwZdOrJ5K6L6L3W56tT1517I7DCoGTdMI9j+xF2hbWr5pqct2izXG7tpxnx3Q4STSxuD9qx04Nslc0qLY9zxkOtGQc/yZsttKNLcTq2cIjoA5CpWD+NWKbWEY3XLblI6jZckkQVLpAHeJgjAxn4lqOU0+2yrk0rHnV/l7QPGxpaA+Fri/D4emhRHbJSMHZ42OxyHqlmb0u0u06LzTCTkThuPA/7QlYBwVSSfw0VKSK5MVIueTw=
